# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lizpdx's blog
email: l1z9dx@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Things. And stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lizpdx.github.com" # the base hostname & protocol for your site
twitter_username: l1z9dx
github_username:  lizpdx

# Build settings
markdown: kramdown
