# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lizpdx github site
email: liz.savage@me.com
description: > # this means to ignore newlines until "baseurl:"
  These pages are the start of a github portfolio for Liz Savage.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lizpdx.github.io" # the base hostname & protocol for your site
twitter_username: lizthedrummer
github_username:  lizpdx

# Build settings
markdown: kramdown
